<a href="https://colab.research.google.com/github/andrewdaitruong/Truong_Zhou_DelaTorre_HW4/blob/main/Truong_Zhou_DelaTorre_HW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Names



*   Andrew Truong
*   Alex Zhou
*   Oscar DelaTorre

# 1. Consider the two tables shown below-called population and countyseats.

In [ ]:
import pandas as pd

In [ ]:
population = pd.DataFrame (
   { "state": ["California", "California", "California", "California"],
    "county": ["Orange", "Orange", "Los Angeles", "Los Angeles"],
    "year": [2000, 2010, 2000, 2010],
    "population": [2846289, 3010232, 3694820, 3792621]
   }
)

In [ ]:
population.index = range(1, len(population) + 1)
population

        state       county  year  population
1  California       Orange  2000     2846289
2  California       Orange  2010     3010232
3  California  Los Angeles  2000     3694820
4  California  Los Angeles  2010     3792621

In [ ]:
countyseats = pd.DataFrame (
    { "statename": ["California", "California", "California", "Oregon"],
    "countyname": ["Orange", "Los Angeles", "San Diego", "Wasco"],
    "countyseat": ["Santa Ana", "Los Angeles", "San Diego", "The Dalles"]
    }
)

In [ ]:
countyseats.index = range(1, len(countyseats) + 1)
countyseats

    statename   countyname   countyseat
1  California       Orange    Santa Ana
2  California  Los Angeles  Los Angeles
3  California    San Diego    San Diego
4      Oregon        Wasco   The Dalles

# a)

In [ ]:
countyseats_rename = countyseats.copy()
countyseats_rename = countyseats_rename.rename(columns={"countyname": "county", "statename": "state"})

In [ ]:
pd.merge(population, countyseats_rename)

        state       county  year  population   countyseat
0  California       Orange  2000     2846289    Santa Ana
1  California       Orange  2010     3010232    Santa Ana
2  California  Los Angeles  2000     3694820  Los Angeles
3  California  Los Angeles  2010     3792621  Los Angeles

# b)

In [ ]:
pd.merge(population, countyseats, left_on="state", right_on="statename")

,state,county,year,population,statename,countyname,countyseat
0,California,Orange,2000,2846289,California,Orange,Santa Ana
1,California,Orange,2000,2846289,California,Los Angeles,Los Angeles
2,California,Orange,2000,2846289,California,San Diego,San Diego
3,California,Orange,2010,3010232,California,Orange,Santa Ana
4,California,Orange,2010,3010232,California,Los Angeles,Los Angeles
5,California,Orange,2010,3010232,California,San Diego,San Diego
6,California,Los Angeles,2000,3694820,California,Orange,Santa Ana
7,California,Los Angeles,2000,3694820,California,Los Angeles,Los Angeles
8,California,Los Angeles,2000,3694820,California,San Diego,San Diego
9,California,Los Angeles,2010,3792621,California,Orange,Santa Ana
10,California,Los Angeles,2010,3792621,California,Los Angeles,Los Angeles
11,California,Los Angeles,2010,3792621,California,San Diego,San Diego

# c)

In [ ]:
pd.merge(population, countyseats, left_on=["state", "county"], right_on=["statename", "countyname"])

,state,county,year,population,statename,countyname,countyseat
0,California,Orange,2000,2846289,California,Orange,Santa Ana
1,California,Orange,2010,3010232,California,Orange,Santa Ana
2,California,Los Angeles,2000,3694820,California,Los Angeles,Los Angeles
3,California,Los Angeles,2010,3792621,California,Los Angeles,Los Angeles

# d)

In [ ]:
concat_df = pd.concat([population, countyseats], axis=1)
concat_df

,state,county,year,population,statename,countyname,countyseat
1,California,Orange,2000,2846289,California,Orange,Santa Ana
2,California,Orange,2010,3010232,California,Los Angeles,Los Angeles
3,California,Los Angeles,2000,3694820,California,San Diego,San Diego
4,California,Los Angeles,2010,3792621,Oregon,Wasco,The Dalles

# 2.

In [ ]:
df = pd.read_csv('billboard.csv', encoding='ISO-8859-1')
df

,year,artist.inverted,track,time,genre,date.entered,date.peaked,x1st.week,x2nd.week,x3rd.week,...,x67th.week,x68th.week,x69th.week,x70th.week,x71st.week,x72nd.week,x73rd.week,x74th.week,x75th.week,x76th.week
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,78,63.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,15,8.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,71,48.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,41,23.0,18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,57,47.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,2000,Ghostface Killah,Cherchez LaGhost,3:04,R&B,2000-08-05,2000-08-05,98,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,2000,"Smith, Will",Freakin' It,3:58,Rap,2000-02-12,2000-02-12,99,99.0,99.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,2000,Zombie Nation,Kernkraft 400,3:30,Rock,2000-09-02,2000-09-02,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,2000,"Eastsidaz, The",Got Beef,3:58,Rap,2000-07-01,2000-07-01,99,99.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,2000,Fragma,Toca's Miracle,3:22,R&B,2000-10-28,2000-10-28,99,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
week_columns = [col for col in df.columns if 'week' in col]
tidy_df = df.melt(id_vars=["year", "artist.inverted", "track", "time", "genre", "date.entered", "date.peaked"],
                  value_vars=week_columns,
                  var_name="week", value_name="rank")

In [ ]:
tidy_df = tidy_df.dropna(subset=["rank"])
tidy_df.reset_index(drop=True, inplace=True)
tidy_df

,year,artist.inverted,track,time,genre,date.entered,date.peaked,week,rank
0,2000,Destiny's Child,Independent Women Part I,3:38,Rock,2000-09-23,2000-11-18,x1st.week,78.0
1,2000,Santana,"Maria, Maria",4:18,Rock,2000-02-12,2000-04-08,x1st.week,15.0
2,2000,Savage Garden,I Knew I Loved You,4:07,Rock,1999-10-23,2000-01-29,x1st.week,71.0
3,2000,Madonna,Music,3:45,Rock,2000-08-12,2000-09-16,x1st.week,41.0
4,2000,"Aguilera, Christina",Come On Over Baby (All I Want Is You),3:38,Rock,2000-08-05,2000-10-14,x1st.week,57.0
...,...,...,...,...,...,...,...,...,...
5302,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,x63rd.week,45.0
5303,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,x63rd.week,50.0
5304,2000,Lonestar,Amazed,4:25,Country,1999-06-05,2000-03-04,x64th.week,50.0
5305,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,x64th.week,50.0
5306,2000,Creed,Higher,5:16,Rock,1999-09-11,2000-07-22,x65th.week,49.0

# a) Show for each track, how many weeks it spent on the chart

In [ ]:
weeks = tidy_df.groupby("track")["week"].nunique()
weeks

track
(Hot S**t) Country Grammar      34
3 Little Words                   9
911                             19
A Country Boy Can Survive        3
A Little Gasoline                6
                                ..
You Won't Be Lonely Now         13
You'll Always Be Loved By Me    19
You're A God                    21
Your Everything                 16
www.memory                      15
Name: week, Length: 316, dtype: int64

# b) List tracks in decreasing order of number of weeks spent on the chart

In [ ]:
weeks_descend = weeks.sort_values(ascending=False)
weeks_descend

track
Higher                   57
Amazed                   55
Kryptonite               53
Breathe                  53
With Arms Wide Open      47
                         ..
Deck The Halls            2
Souljas                   1
Toca's Miracle            1
No Me Dejes De Querer     1
Cherchez LaGhost          1
Name: week, Length: 316, dtype: int64

# c) Show for each track, its top rank

In [ ]:
top_rank = tidy_df.groupby("track")["rank"].min()
top_rank

track
(Hot S**t) Country Grammar       7.0
3 Little Words                  89.0
911                             38.0
A Country Boy Can Survive       75.0
A Little Gasoline               75.0
                                ...
You Won't Be Lonely Now         80.0
You'll Always Be Loved By Me    55.0
You're A God                    23.0
Your Everything                 51.0
www.memory                      45.0
Name: rank, Length: 316, dtype: float64

# d) List tracks in increasing order of its top rank

In [ ]:
top_rank_ascend = top_rank.sort_values()
top_rank_ascend

track
Doesn't Really Matter     1.0
Incomplete                1.0
Say My Name               1.0
Be With You               1.0
Thank God I Found You     1.0
                         ...
I Know                   98.0
Freakin' It              99.0
Kernkraft 400            99.0
Got Beef                 99.0
Toca's Miracle           99.0
Name: rank, Length: 316, dtype: float64

# e) Show for each artist, their top rank

In [ ]:
top_rank_artist = tidy_df.groupby("artist.inverted")["rank"].min()
top_rank_artist

artist.inverted
2 Pac               72.0
2Ge+her             87.0
3 Doors Down         3.0
504 Boyz            17.0
98¡                  2.0
                    ...
Yankee Grey         74.0
Yearwood, Trisha    81.0
Ying Yang Twins     74.0
Zombie Nation       99.0
matchbox twenty      1.0
Name: rank, Length: 228, dtype: float64

# f) List artists in increasing order of their top rank

In [ ]:
top_artist_ascend = top_rank_artist.sort_values(ascending=False)
top_artist_ascend

artist.inverted
Zombie Nation       99.0
Smith, Will         99.0
Fragma              99.0
Ghostface Killah    98.0
LL Cool J           98.0
                    ...
Lonestar             1.0
Madonna              1.0
N'Sync               1.0
Santana              1.0
matchbox twenty      1.0
Name: rank, Length: 228, dtype: float64

# g) List tracks that spent more than 35 weeks in the charts

In [ ]:
weeks_spent = tidy_df.groupby("track")["week"].nunique()
tracks_over_35_weeks = weeks_spent[weeks_spent > 35]
tracks_over_35_weeks

track
Amazed                  55
Bent                    39
Breathe                 53
Everything You Want     41
He Wasn't Man Enough    37
Higher                  57
I Wanna Know            44
Kryptonite              53
With Arms Wide Open     47
Name: week, dtype: int64

# h) List tracks that spent more than 35 weeks in the charts along with their artists

In [ ]:
weeks_artist = tidy_df.groupby(["track", "artist.inverted"])["week"].nunique()
tracks_and_artists_over_35_weeks = weeks_artist[weeks_artist > 35]
tracks_and_artists_over_35_weeks

track                 artist.inverted
Amazed                Lonestar            55
Bent                  matchbox twenty     39
Breathe               Hill, Faith         53
Everything You Want   Vertical Horizon    41
He Wasn't Man Enough  Braxton, Toni       37
Higher                Creed               57
I Wanna Know          Joe                 44
Kryptonite            3 Doors Down        53
With Arms Wide Open   Creed               47
Name: week, dtype: int64

# 3.

In [ ]:
demo = pd.read_csv("demographics.csv")
demo

,Country Name,Country Code,Series Name,Series Code,YR2015
0,Afghanistan,AFG,"Life expectancy at birth, total (years)",SP.DYN.LE00.IN,63.377
1,Afghanistan,AFG,Urban population,SP.URB.TOTL,8535606
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,34413603
3,Afghanistan,AFG,"Population ages 80 and above, female",SP.POP.80UP.FE,48319
4,Afghanistan,AFG,"Population ages 80 and above, male",SP.POP.80UP.MA,37233
...,...,...,...,...,...
3880,Zimbabwe,ZWE,"Mortality rate, adult, male (per 1,000 male ad...",SP.DYN.AMRT.MA,396.789
3881,Zimbabwe,ZWE,"Population, female",SP.POP.TOTL.FE.IN,7245857
3882,Zimbabwe,ZWE,"Population, male",SP.POP.TOTL.MA.IN,6568772
3883,Zimbabwe,ZWE,"Population ages 65 and above, female",SP.POP.65UP.FE.IN,254913
3884,Zimbabwe,ZWE,"Population ages 65 and above, male",SP.POP.65UP.MA.IN,138008

# (a) The data is not “tidy”. In 2-3 sentences, explain why.

One reason is because there are multiple observations in a single row (Ex: row 3 observes both population ages 80+ and female). The column "Series Name" also has many data (Ex: population, sex, etc) which should ideally be spread in multiple columns.

# (b) Transform the table to tidy data with one country per row. [Give code]

In [ ]:
tidy_demo = demo.pivot_table(index=["Country Name", "Country Code"], columns="Series Code", values="YR2015", aggfunc="first").reset_index()
tidy_demo

Series Code,Country Name,Country Code,SP.DYN.AMRT.FE,SP.DYN.AMRT.MA,SP.DYN.LE00.IN,SP.POP.0014.FE.IN,SP.POP.0014.MA.IN,SP.POP.1564.FE.IN,SP.POP.1564.MA.IN,SP.POP.65UP.FE.IN,SP.POP.65UP.MA.IN,SP.POP.80UP.FE,SP.POP.80UP.MA,SP.POP.TOTL,SP.POP.TOTL.FE.IN,SP.POP.TOTL.MA.IN,SP.URB.TOTL
0,Afghanistan,AFG,206.746,248.724,63.377,7538168,7905639,8730445,9386355,458824,394172,48319,37233,34413603,16727437,17686166,8535606
1,Albania,ALB,51.195,99.215,78.025,252745,285043,972981,1006194,188520,175220,37747,29218,2880703,1414246,1466457,1654503
2,Algeria,DZA,84.44,107.191,76.09,5583284,5821646,12878041,13115548,1202806,1126700,238417,215324,39728025,19664131,20063894,28146511
3,American Samoa,ASM,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,55812,NA,NA,48689
4,Andorra,AND,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,78011,NA,NA,68919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,West Bank and Gaza,PSE,96.217,132.282,73.442,833551,870349,1202717,1234672,67095,61708,9166,6352,4270092,2103363,2166729,3218283
255,World,WLD,116.083524344293,174.085100929693,71.9478983340412,929387550,994233917,2374510877,2436229220,334592898,268784892,76126964,46378645,7340548192,3638491322,3699248029,3956546394
256,"Yemen, Rep.",YEM,198.071,244.968,66.085,5284293,5498189,7455072,7519477,402324,338534,50563,35613,26497889,13141689,13356200,9215171
257,Zambia,ZMB,255.312,350.332,61.737,3638859,3694945,4183972,4034982,199363,127240,26046,10615,15879361,8022194,7857167,6654564
258,Zimbabwe,ZWE,339.493,396.789,59.534,2932133,2946312,4058811,3484452,254913,138008,41491,14032,13814629,7245857,6568772,4473868

# (c) Add the male/female population numbers together (i.e., ignore sex-related differences).

In [ ]:
tidy_demo.columns

Index(['Country Name', 'Country Code', 'SP.DYN.AMRT.FE', 'SP.DYN.AMRT.MA',
       'SP.DYN.LE00.IN', 'SP.POP.0014.FE.IN', 'SP.POP.0014.MA.IN',
       'SP.POP.1564.FE.IN', 'SP.POP.1564.MA.IN', 'SP.POP.65UP.FE.IN',
       'SP.POP.65UP.MA.IN', 'SP.POP.80UP.FE', 'SP.POP.80UP.MA', 'SP.POP.TOTL',
       'SP.POP.TOTL.FE.IN', 'SP.POP.TOTL.MA.IN', 'SP.URB.TOTL'],
      dtype='object', name='Series Code')

In [ ]:
column_pairs = [
    ("SP.DYN.AMRT.FE", "SP.DYN.AMRT.MA"),
    ("SP.POP.0014.FE.IN", "SP.POP.0014.MA.IN"),
    ("SP.POP.1564.FE.IN", "SP.POP.1564.MA.IN"),
    ("SP.POP.65UP.FE.IN", "SP.POP.65UP.MA.IN"),
    ("SP.POP.80UP.FE", "SP.POP.80UP.MA")
]

In [ ]:
fe_columns = [col for col in tidy_demo.columns if '.FE' in col]
ma_columns = [col.replace('.FE', '.MA') for col in fe_columns if col.replace('.FE', '.MA') in tidy_demo.columns]

In [ ]:
for fe_col, ma_col in zip(fe_columns, ma_columns):
    new_col = fe_col.replace('.FE', '')
    fe_values = pd.to_numeric(tidy_demo[fe_col], errors="coerce").astype(float)
    ma_values = pd.to_numeric(tidy_demo[ma_col], errors="coerce").astype(float)
    tidy_demo[new_col] = fe_values + ma_values

In [ ]:
tidy_demo = tidy_demo.drop(columns=fe_columns + ma_columns)
pd.set_option('display.float_format', lambda x: '%.15g' % x)
tidy_demo

Series Code,Country Name,Country Code,SP.DYN.LE00.IN,SP.POP.TOTL,SP.URB.TOTL,SP.DYN.AMRT,SP.POP.0014.IN,SP.POP.1564.IN,SP.POP.65UP.IN,SP.POP.80UP,SP.POP.TOTL.IN
0,Afghanistan,AFG,63.377,34413603,8535606,455.47,15443807,18116800,852996,85552,34413603
1,Albania,ALB,78.025,2880703,1654503,150.41,537788,1979175,363740,66965,2880703
2,Algeria,DZA,76.09,39728025,28146511,191.631,11404930,25993589,2329506,453741,39728025
3,American Samoa,ASM,NA,55812,48689,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,AND,NA,78011,68919,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
254,West Bank and Gaza,PSE,73.442,4270092,3218283,228.499,1703900,2437389,128803,15518,4270092
255,World,WLD,71.9478983340412,7340548192,3956546394,290.168625273986,1923621467,4810740097,603377790,122505609,7337739351
256,"Yemen, Rep.",YEM,66.085,26497889,9215171,443.039,10782482,14974549,740858,86176,26497889
257,Zambia,ZMB,61.737,15879361,6654564,605.644,7333804,8218954,326603,36661,15879361
258,Zimbabwe,ZWE,59.534,13814629,4473868,736.282,5878445,7543263,392921,55523,13814629

# d) Write code to show the top 5 countries with the lowest proportion of the population below 14 years old [Code, and list of 5 countries]

In [ ]:
tidy_demo['SP.POP.0014.IN'] = pd.to_numeric(tidy_demo['SP.POP.0014.IN'], errors='coerce')
tidy_demo['SP.POP.TOTL'] = pd.to_numeric(tidy_demo['SP.POP.TOTL'], errors='coerce')

lowest_proportion = tidy_demo[['Country Name', 'SP.POP.0014.IN', 'SP.POP.TOTL']].copy()

lowest_proportion.loc[:, 'proportion_below_14'] = lowest_proportion['SP.POP.0014.IN'] / lowest_proportion['SP.POP.TOTL']

lowest_proportion_sorted = lowest_proportion.sort_values(by="proportion_below_14").head(5)

lowest_proportion_sorted[['Country Name', 'proportion_below_14']]

Series Code      Country Name  proportion_below_14
10                      Aruba           917.759462
140          Macao SAR, China          6103.688361
146                     Malta          6882.175136
42            Channel Islands          7589.038172
139                Luxembourg          7976.327161

In [ ]:
def colab2pdf():
  # @title Download Notebook in PDF Format{display-mode:'form'}
  !apt-get install -yqq --no-install-recommends librsvg2-bin>/dev/null;
  import contextlib,datetime,google,io,IPython,ipywidgets,json,locale,nbformat,os,pathlib,requests,urllib,warnings,werkzeug,yaml,re;locale.setlocale(locale.LC_ALL,'en_US.UTF-8');warnings.filterwarnings('ignore',category=nbformat.validator.MissingIDFieldWarning);
  %matplotlib inline
  def convert(b):
    try:
      s.value='🔄 Converting';b.disabled=True
      n=pathlib.Path(werkzeug.utils.secure_filename(urllib.parse.unquote(requests.get(f'http://{os.environ["COLAB_JUPYTER_IP"]}:{os.environ["KMP_TARGET_PORT"]}/api/sessions').json()[0]['name'])))
      p=pathlib.Path('/content/pdfs')/f'{datetime.datetime.utcnow().strftime("%Y%m%d_%H%M%S")}_{n.stem}';p.mkdir(parents=True,exist_ok=True);nb=nbformat.reads(json.dumps(google.colab._message.blocking_request('get_ipynb',timeout_sec=600)['ipynb']),as_version=4)
      u=[u for c in nb.cells if c.get('cell_type')=='markdown' for u in re.findall(r'!\[.*?\]\((https?://.*?)\)',c['source']) if requests.head(u,timeout=5).status_code!=200]
      if u:raise Exception(f"Bad Image URLs: {','.join(u)}")
      nb.cells=[cell for cell in nb.cells if '--Colab2PDF' not in cell.source]
      nb=nbformat.v4.new_notebook(cells=nb.cells or [nbformat.v4.new_code_cell('#')]);nbformat.validator.normalize(nb)
      nbformat.write(nb,(p/f'{n.stem}.ipynb').open('w',encoding='utf-8'))
      with (p/'config.yml').open('w', encoding='utf-8') as f: yaml.dump({'include-in-header':[{'text':r'\usepackage{fvextra}\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaksymbolleft={},showspaces=false,showtabs=false,breaklines,breakanywhere,commandchars=\\\{\}}'}],'include-before-body':[{'text':r'\DefineVerbatimEnvironment{verbatim}{Verbatim}{breaksymbolleft={},showspaces=false,showtabs=false,breaklines}'}]},f)
      !quarto render {p}/{n.stem}.ipynb --metadata-file={p}/config.yml --to pdf -M latex-auto-install -M margin-top=1in -M margin-bottom=1in -M margin-left=1in -M margin-right=1in --quiet
      google.colab.files.download(str(p/f'{n.stem}.pdf'));s.value=f'✅ Downloaded: {n.stem}.pdf'
    except Exception as e:s.value=f'❌ {str(e)}'
    finally:b.disabled=False
  if not pathlib.Path('/usr/local/bin/quarto').exists():
    !wget -q 'https://quarto.org/download/latest/quarto-linux-amd64.deb' && dpkg -i quarto-linux-amd64.deb>/dev/null && quarto install tinytex --update-path --quiet && rm quarto-linux-amd64.deb
  b=ipywidgets.widgets.Button(description='⬇️ Download');s=ipywidgets.widgets.Label();b.on_click(lambda b:convert(b));IPython.display.display(ipywidgets.widgets.HBox([b,s]))
colab2pdf() # | Colab2PDF v1.6 | https://github.com/drengskapur/colab2pdf | GPL-3.0-or-later |

HBox(children=(Button(description='⬇️ Download', style=ButtonStyle()), Label(value='')))